# Generated by Django 5.2.7 on 2025-11-05 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('laser_cutting', 'Laser Cutting'), ('press_brake', 'Press Brake'), ('tube_laser', 'Tube Laser Cutting')], max_length=50)),
                ('working_area', models.CharField(blank=True, max_length=200, null=True)),
                ('laser_source_power', models.CharField(blank=True, max_length=200, null=True)),
                ('compressor', models.BooleanField(default=False)),
                ('stabilizer', models.BooleanField(default=False)),
                ('bevel_laser_head', models.BooleanField(default=False)),
                ('bending_capacity', models.CharField(blank=True, max_length=200, null=True)),
                ('working_length', models.CharField(blank=True, max_length=200, null=True)),
                ('press_brake_type', models.CharField(blank=True, max_length=200, null=True)),
                ('CNC_type', models.CharField(blank=True, choices=[('DA_53T', 'Delem DA-53T'), ('DA_69T', 'Delem DA-69T'), ('DA_66T', 'Delem DA-66T')], max_length=200, null=True)),
                ('axis_type', models.CharField(blank=True, choices=[('6_1', '6+1 Axis'), ('4_1', '4+1 Axis')], max_length=200, null=True)),
                ('tube_length', models.CharField(blank=True, max_length=200, null=True)),
                ('tube_diameter', models.CharField(blank=True, max_length=200, null=True)),
                ('length_of_unloading_table', models.CharField(blank=True, max_length=200, null=True)),
                ('automatic_loading', models.BooleanField(default=False)),
                ('semi_automatic_loading', models.BooleanField(default=False)),
                ('manual_loading', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
