# Generated by Django 5.2.7 on 2025-11-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='press_brake_type',
        ),
    ]
