# Generated by Django 5.2.7 on 2025-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_quote_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['completed']},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AlterField(
            model_name='quote',
            name='machine_type',
            field=models.CharField(choices=[('laser_cutting', 'Laser Cutting Machine'), ('press_brake', 'Press Brake'), ('tube_laser', 'Tube Laser Cutting Machine')], max_length=50),
        ),
    ]
