# Generated by Django 5.2.7 on 2025-11-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_quote_created_at_quote_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
    ]
