# Generated by Django 5.2.7 on 2025-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_quote_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
