# Generated by Django 5.2.7 on 2025-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_quote_options_quote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='request_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
