# Generated by Django 5.2.7 on 2025-11-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_quote_request_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='request_text',
        ),
    ]
