# Generated by Django 5.2.7 on 2025-11-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_quote_request_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='quote_attachments/%Y/%m/%d/'),
        ),
    ]
