# Generated by Django 5.2.7 on 2025-11-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_quote_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='three_chucks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='two_chucks',
            field=models.BooleanField(default=False),
        ),
    ]
