# Generated by Django 5.2.7 on 2025-11-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_quote_three_chucks_quote_two_chucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='automatic_loading',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='manual_loading',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='semi_automatic_loading',
        ),
        migrations.AddField(
            model_name='quote',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic'), ('manual', 'Manual')], max_length=20),
        ),
    ]
