# Generated by Django 5.2.7 on 2025-11-11 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_quote_automatic_loading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='CNC_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='axis_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='bending_capacity',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='bevel_laser_head',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='compressor',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='laser_source_power',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='length_of_unloading_table',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='loading_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='stabilizer',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='three_chucks',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tube_diameter',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tube_length',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='two_chucks',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='working_area',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='working_length',
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LaserCuttingSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_area', models.CharField(blank=True, max_length=200, null=True)),
                ('laser_source_power', models.CharField(blank=True, max_length=200, null=True)),
                ('compressor', models.BooleanField(default=False)),
                ('stabilizer', models.BooleanField(default=False)),
                ('bevel_laser_head', models.BooleanField(default=False)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lasercuttingspec', to='base.quote')),
            ],
        ),
        migrations.CreateModel(
            name='PressBrakeSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bending_capacity', models.CharField(blank=True, max_length=200, null=True)),
                ('working_length', models.CharField(blank=True, max_length=200, null=True)),
                ('CNC_type', models.CharField(blank=True, choices=[('DA_53T', 'Delem DA-53T'), ('DA_69T', 'Delem DA-69T'), ('DA_66T', 'Delem DA-66T')], max_length=200, null=True)),
                ('axis_type', models.CharField(blank=True, choices=[('6_1', '6+1 Axis'), ('4_1', '4+1 Axis')], max_length=200, null=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pressbrakespec', to='base.quote')),
            ],
        ),
        migrations.CreateModel(
            name='TubeLaserSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_length', models.CharField(blank=True, max_length=200, null=True)),
                ('tube_diameter', models.CharField(blank=True, max_length=200, null=True)),
                ('length_of_unloading_table', models.CharField(blank=True, max_length=200, null=True)),
                ('loading_type', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic'), ('manual', 'Manual')], max_length=20)),
                ('two_chucks', models.BooleanField(default=False)),
                ('three_chucks', models.BooleanField(default=False)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tubelaserspec', to='base.quote')),
            ],
        ),
    ]
