# Generated by Django 5.2.7 on 2025-11-11 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_quote_cnc_type_remove_quote_axis_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasercuttingspec',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.quote'),
        ),
        migrations.AlterField(
            model_name='pressbrakespec',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.quote'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.quote'),
        ),
    ]
