# Generated by Django 5.2.7 on 2025-11-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_lasercuttingspec_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='machine_type',
            field=models.CharField(choices=[('laser_cutting', 'Laser Cutting'), ('press_brake', 'Press Brake'), ('tube_laser', 'Tube Laser Cutting'), ('other', 'Other')], max_length=50),
        ),
    ]
