# Generated by Django 5.2.7 on 2025-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_quote_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasercuttingspec',
            name='cabinet_protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lasercuttingspec',
            name='interchangeable_tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lasercuttingspec',
            name='tube_cutting_modeule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tubelaserspec',
            name='tube_cutting_module',
            field=models.BooleanField(default=False, verbose_name='Tube Cutting Module'),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='length_of_unloading_table',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Length of Unloading Table (e.g. 3000 mm)'),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='Loading Type'),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='three_chucks',
            field=models.BooleanField(default=False, verbose_name='Three Chucks'),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='tube_diameter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tube Diameter (e.g. 300 mm)'),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='tube_length',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tube Length (e.g. 6000 mm)'),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='two_chucks',
            field=models.BooleanField(default=False, verbose_name='Two Chucks'),
        ),
    ]
