# Generated by Django 5.2.7 on 2025-11-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_lasercuttingspec_cabinet_protection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lasercuttingspec',
            old_name='tube_cutting_modeule',
            new_name='tube_cutting_module',
        ),
        migrations.RemoveField(
            model_name='tubelaserspec',
            name='tube_cutting_module',
        ),
        migrations.AddField(
            model_name='lasercuttingspec',
            name='tube_diameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lasercuttingspec',
            name='tube_length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='length_of_unloading_table',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='three_chucks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='tube_diameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='tube_length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tubelaserspec',
            name='two_chucks',
            field=models.BooleanField(default=False),
        ),
    ]
