# Generated by Django 5.2.7 on 2025-11-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_tube_cutting_modeule_lasercuttingspec_tube_cutting_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasercuttingspec',
            name='tube_diameter',
        ),
        migrations.RemoveField(
            model_name='lasercuttingspec',
            name='tube_length',
        ),
    ]
