# Generated by Django 5.2.7 on 2025-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_lasercuttingspec_tube_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasercuttingspec',
            name='tube_diameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lasercuttingspec',
            name='tube_length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
