# Generated by Django 5.2.7 on 2025-11-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_lasercuttingspec_tube_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasercuttingspec',
            name='tube_diameter',
        ),
        migrations.RemoveField(
            model_name='lasercuttingspec',
            name='tube_length',
        ),
    ]
