# Generated by Django 5.2.7 on 2025-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_lasercuttingspec_tube_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasercuttingspec',
            name='tube_module_diameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lasercuttingspec',
            name='tube_module_length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
