# Generated by Django 5.2.7 on 2025-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_lasercuttingspec_tube_module_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubelaserspec',
            name='laser_source_power',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
