# Generated by Django 5.2.7 on 2025-11-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_tubelaserspec_laser_source_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubelaserspec',
            name='bevel_laser_head',
            field=models.BooleanField(default=False),
        ),
    ]
